# .streamlit/config.toml

[server]
headless = true
port = 8501  # Replace with the port number you want to use locally
enableCORS = true

[theme]
primaryColor = '#FF8C02'  # Bright Orange
backgroundColor = '#000000'  # Black Background
secondaryBackgroundColor = '#303030'  # Dark Grey for secondary background
textColor = '#FFFFFF'  # White text for better readability

# Fonts
font = "sans serif"

# Additional settings for a more professional look
[layout]
wideMode = true
sidebarWidth = 300

[header]
title = "YouTube Video Summarizer"
subtitle = "Summarize, Translate, and Generate Videos Effortlessly"

[footer]
footerText = "© 2024 Your Company Name. All rights reserved."
footerColor = "#FF8C02"  # Bright Orange to match the primary color

[widgets]
spacing = "10px"
borderRadius = "5px"
boxShadow = "0 4px 8px 0 rgba(0, 0, 0, 0.2)"

# Custom CSS to enhance the look and feel
[custom_css]
css = """
<style>
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background-color: #000000;
    color: #FFFFFF;
}
.stButton>button {
    background-color: #FF8C02;
    color: white;
    border-radius: 5px;
    padding: 10px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}
.stTextInput>div>input {
    background-color: #333333;
    color: #FFFFFF;
    border: 1px solid #E0E0E0;
    border-radius: 5px;
    padding: 10px;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
}
.stSelectbox>div>div>div>div {
    background-color: #333333;
    color: #FFFFFF;
    border: 1px solid #E0E0E0;
    border-radius: 5px;
    padding: 10px;
    box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
}
.stMarkdown>div {
    color: #FFFFFF;
}
footer {
    color: #FF8C02;
    font-size: 14px;
    text-align: center;
    margin-top: 20px;
    padding: 20px 0;
    background-color: #000000;
}
</style>
"""
